-- FormFlow — Patch 002: תמיכה באפליקציית React (workspace meta, מזהים מספריים, בדיקת ערך ייחודי)

-- פרופיל Workspace (שם עסק, טלפון, דומיין, מטרה) על רשומת הלקוח
alter table public.clients
  add column if not exists meta jsonb not null default '{}'::jsonb;

-- מזהה מספרי רץ לתגובות (הממשק עובד עם id מספרי)
alter table public.responses
  add column if not exists seq bigint generated by default as identity;
create unique index if not exists idx_responses_seq on public.responses(seq);

-- בדיקת "ערך ייחודי" בטופס — רץ בצד השרת כדי לעבוד גם לממלא אנונימי
create or replace function public.is_value_taken(p_form uuid, p_key text, p_value text)
returns boolean
language sql security definer set search_path = public
stable as $$
  select exists (
    select 1 from public.responses
    where form_id = p_form
      and data->'values'->>p_key = p_value
  );
$$;

grant execute on function public.is_value_taken(uuid, text, text) to anon, authenticated;

notify pgrst, 'reload schema';
