/** Canonical seed data — single source for the API server and the frontend fallback. */

export const FORM_ID = 'conf-2026'
export const FORM_SLUG = 'product-conf-2026'
export const FORM_NAME = 'הרשמה לכנס המוצר 2026'

export const seedFields = [
  {
    id: 'fld-member',
    type: 'radio',
    label: 'חברת מועדון שווה?',
    required: true,
    fieldKey: 'member',
    options: ['כן, חברי מועדון', 'עדיין לא'],
    page: 1,
  },
  {
    id: 'fld-participants',
    type: 'number',
    label: 'מספר משתתפים',
    placeholder: 'למשל: 2',
    required: true,
    fieldKey: 'participants',
    page: 1,
  },
  {
    id: 'fld-first',
    type: 'short_text',
    label: 'שם פרטי',
    placeholder: 'ישראל',
    required: true,
    fieldKey: 'first_name',
    half: true,
    page: 2,
  },
  {
    id: 'fld-last',
    type: 'short_text',
    label: 'שם משפחה',
    placeholder: 'ישראלי',
    required: true,
    fieldKey: 'last_name',
    half: true,
    page: 2,
  },
  {
    id: 'fld-email',
    type: 'email',
    label: 'כתובת מייל',
    placeholder: 'name@company.co.il',
    help: 'אישור ההרשמה יישלח לכתובת זו',
    required: true,
    unique: true,
    errorMessage: 'נא להזין כתובת מייל תקינה',
    fieldKey: 'email',
    page: 2,
  },
  {
    id: 'fld-track',
    type: 'radio',
    label: 'באיזה מסלול תשתתפו?',
    required: true,
    fieldKey: 'track',
    options: ['מוצר וניהול', 'פיתוח והנדסה', 'עיצוב ו-UX'],
    page: 2,
  },
  {
    id: 'fld-workshop',
    type: 'dropdown',
    label: 'בחירת סדנת עיצוב',
    help: 'מוצג רק למסלול עיצוב ו-UX (כלל לוגיקה)',
    required: false,
    fieldKey: 'design_workshop',
    options: ['Design Systems בעברית', 'מחקר משתמשים מהיר', 'פרוטוטייפינג ב-Figma'],
    page: 2,
  },
  {
    id: 'fld-notes',
    type: 'long_text',
    label: 'הערות והעדפות (אופציונלי)',
    placeholder: 'נגישות, תזונה, כל דבר שנצטרך לדעת…',
    required: false,
    fieldKey: 'notes',
    page: 3,
  },
  {
    id: 'fld-terms',
    type: 'radio',
    label: 'אישור תקנון',
    required: true,
    fieldKey: 'terms',
    options: ['קראתי ואני מאשר/ת את תנאי ההשתתפות'],
    page: 3,
  },
]

export const seedRules = [
  {
    id: 'rule-1',
    name: 'הצגת שדות סדנה למסלול עיצוב',
    scope: 'fill',
    enabled: true,
    combinator: 'and',
    conditions: [{ fieldKey: 'track', op: 'eq', value: 'עיצוב ו-UX' }],
    actions: [{ type: 'show_field', fieldKey: 'design_workshop' }],
  },
  {
    id: 'rule-2',
    name: 'ניתוב פניות VIP למייל מנהלת האירוע',
    scope: 'submit',
    enabled: true,
    combinator: 'and',
    conditions: [
      { fieldKey: 'participants', op: 'gt', value: '5' },
      { fieldKey: 'member', op: 'eq', value: 'כן, חברי מועדון' },
    ],
    actions: [
      { type: 'route_email', to: 'vip@shaveh360.co.il' },
      { type: 'add_tag', text: 'VIP', color: 'peach' },
    ],
  },
  {
    id: 'rule-3',
    name: 'דילוג על עמוד פרטים לחברי מועדון',
    scope: 'fill',
    enabled: false,
    combinator: 'and',
    conditions: [{ fieldKey: 'member', op: 'eq', value: 'כן, חברי מועדון' }],
    actions: [{ type: 'jump_page', page: 3, label: '3 · סיכום' }],
  },
]

const minutesAgo = (m) => new Date(Date.now() - m * 60_000).toISOString()

export const seedSubmissions = [
  {
    id: 1128,
    values: {
      member: 'כן, חברי מועדון',
      participants: '7',
      first_name: 'נועה',
      last_name: 'ברק',
      email: 'noa@acme.co.il',
      track: 'מוצר וניהול',
      terms: 'קראתי ואני מאשר/ת את תנאי ההשתתפות',
    },
    name: 'נועה ברק',
    email: 'noa@acme.co.il',
    track: 'מוצר וניהול',
    tags: [{ text: 'VIP', color: 'peach' }],
    status: 'new',
    notes: '',
    submittedAt: minutesAgo(4),
  },
  {
    id: 1127,
    values: {
      member: 'עדיין לא',
      participants: '1',
      first_name: 'אמיר',
      last_name: 'כהן',
      email: 'amir.c@gmail.com',
      track: 'פיתוח והנדסה',
      terms: 'קראתי ואני מאשר/ת את תנאי ההשתתפות',
    },
    name: 'אמיר כהן',
    email: 'amir.c@gmail.com',
    track: 'פיתוח והנדסה',
    tags: [],
    status: 'in_progress',
    notes: '',
    submittedAt: minutesAgo(22),
  },
  {
    id: 1126,
    values: {
      member: 'עדיין לא',
      participants: '1',
      first_name: 'דנה',
      last_name: 'לוי',
      email: 'dana@studio-d.co',
      track: 'עיצוב ו-UX',
      design_workshop: 'פרוטוטייפינג ב-Figma',
      notes: 'זקוקה לאישור סטודנטית',
      terms: 'קראתי ואני מאשר/ת את תנאי ההשתתפות',
    },
    name: 'דנה לוי',
    email: 'dana@studio-d.co',
    track: 'עיצוב ו-UX',
    tags: [{ text: 'סטודנטית', color: 'purple' }],
    status: 'done',
    notes: 'נשלח אישור הנחה',
    submittedAt: minutesAgo(64),
  },
  {
    id: 1125,
    values: {
      member: 'כן, חברי מועדון',
      participants: '2',
      first_name: 'יוסי',
      last_name: 'מזרחי',
      email: 'yossi@tlv-events.com',
      track: 'מוצר וניהול',
      terms: 'קראתי ואני מאשר/ת את תנאי ההשתתפות',
    },
    name: 'יוסי מזרחי',
    email: 'yossi@tlv-events.com',
    track: 'מוצר וניהול',
    tags: [],
    status: 'done',
    notes: '',
    submittedAt: minutesAgo(183),
  },
]

export const seedNotif = {
  confirmEnabled: true,
  subject: 'קיבלנו את הרשמתך לכנס, {{first_name}} 🎟',
  fromAddress: 'events@shaveh360.co.il',
  attachPdf: true,
  attachIcal: true,
  ownerEnabled: true,
  recipients: ['michal@shaveh360.co.il', 'events@shaveh360.co.il'],
  digest: false,
  smsEnabled: true,
  smsTemplate: 'היי {{first_name}}, נרשמת בהצלחה לכנס המוצר 2026! פרטים וכרטיס: {{short_url}}',
  smsReminder: true,
}

export const seedNotifications = [
  {
    id: 'ntf-1',
    submissionId: 1128,
    channel: 'email',
    recipient: 'noa@acme.co.il',
    status: 'delivered',
    note: 'מייל אישור לממלא',
    at: minutesAgo(4),
  },
  {
    id: 'ntf-2',
    submissionId: 1128,
    channel: 'email',
    recipient: 'vip@shaveh360.co.il',
    status: 'delivered',
    note: 'ניתוב לפי כלל: ניתוב פניות VIP',
    at: minutesAgo(4),
  },
  {
    id: 'ntf-3',
    submissionId: 1128,
    channel: 'sms',
    recipient: '052-•••4821',
    status: 'delivered',
    note: 'SMS אישור לממלא',
    at: minutesAgo(3),
  },
]

export const seedBranding = {
  themeId: 'shaveh',
  primary: '#0d4ef2',
  textColor: '#12265a',
  ctaColor: '#d9f051',
  bgColor: '#e9f2fd',
  headFont: 'Rubik',
  bodyFont: 'Assistant',
  darkMode: 'auto',
}

export function buildSeedDb() {
  return {
    form: {
      id: FORM_ID,
      slug: FORM_SLUG,
      name: FORM_NAME,
      status: 'draft',
      version: 1,
      fields: seedFields,
      rules: seedRules,
      notif: seedNotif,
      branding: seedBranding,
    },
    submissions: seedSubmissions,
    notifications: seedNotifications,
    nextSubmissionId: 1129,
    baseline: { total: 124, completion: 82, avgTime: '2:41', nps: 46 },
  }
}
